# Generated by Django 5.0.7 on 2024-07-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("est_dob", models.DateField()),
                ("weight", models.PositiveSmallIntegerField()),
                ("sex", models.CharField(max_length=1)),
                ("medical_conditions", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("activity", models.CharField(max_length=100)),
                ("notes", models.TextField()),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doginfo.dog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food", models.CharField(max_length=100)),
                ("amount", models.PositiveSmallIntegerField()),
                ("frequency", models.CharField(max_length=100)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doginfo.dog"
                    ),
                ),
            ],
        ),
    ]
