# Generated by Django 5.0.7 on 2024-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doginfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="breed",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="est_dob",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="medical_conditions",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="sex",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="weight",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
