# Generated by Django 5.0.7 on 2024-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doginfo", "0002_alter_dog_breed_alter_dog_est_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="activity",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="feedingschedule",
            name="amount",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="feedingschedule",
            name="food",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="feedingschedule",
            name="frequency",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
