# Generated by Django 5.0.7 on 2024-07-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doginfo", "0003_alter_activitylog_activity_alter_activitylog_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedingschedule",
            name="amount",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
