name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip code
        run: zip -r my_app.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'my_app.zip'
          DEST_DIR: '/'

      - name: Deploy to EC2 via CodeDeploy
        uses: aws-actions/aws-codedeploy-github-actions@v0.0.2
        with:
          application-name: YourCodeDeployApplicationName
          deployment-group-name: YourCodeDeployDeploymentGroupName
          bundle-type: zip
          file-exists-behavior: OVERWRITE
          s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
          s3-key: my_app.zip
